dependencies {
	compileOnly project(":modules:ExpertMicroservice-2:ExpertMicroservice-api")

	restBuilder group: "com.liferay", name: "com.liferay.portal.tools.rest.builder", version: "1.0.222"
	compileOnly group: "com.liferay.portal", name: "release.portal.api", version: "7.4.3.105-ga105"

	compileOnly group: "com.liferay", name: "com.liferay.object.api"

	compileOnly group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.1"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient", version: "4.5"

	// httpmime doit être embarqué dans le JAR car non fourni par Liferay
	compileOnly group: "org.apache.httpcomponents", name: "httpmime", version: "4.5"
}

group = "com.oecci.expert"