# OSGI-INF/liferay/rest/v1_0/recouvrement.properties
#
# Enregistrement du composant REST RecouvrementResource
# dans le framework Liferay Vulcan / JAX-RS.
#
# Ce fichier doit être placé dans :
#   src/main/resources/OSGI-INF/liferay/rest/v1_0/recouvrement.properties

javax.ws.rs.application.select=(osgi.jaxrs.name=ExpertMicroservice.Rest)
javax.ws.rs.resource=true